export const CREATE_CHINESES_REQUEST = 'CREATE_CHINESES_REQUEST';
export const CREATE_CHINESES_SUCCESS = 'CREATE_CHINESES_SUCCESS';
export const CREATE_CHINESES_FAIL = 'CREATE_CHINESES_FAIL';
export const CREATE_CHINESES_RESET = 'CREATE_CHINESES_RESET';

export const GET_ALL_CHINESE_REQUEST = 'GET_ALL_CHINESE_REQUEST ';
export const GET_ALL_CHINESE_SUCCESS = 'GET_ALL_CHINESE_SUCCESS';
export const GET_ALL_CHINESE_FAIL = 'GET_ALL_CHINESE_FAIL';

export const DELETE_CHINESE_REQUEST = 'DELETE_CHINESE_REQUEST';
export const DELETE_CHINESE_SUCCESS = 'DELETE_CHINESE_SUCCESS';
export const DELETE_CHINESE_RESET = 'DELETE_CHINESE_RESET';
export const DELETE_CHINESE_FAIL = 'DELETE_CHINESE_FAIL';

export const GET_CHINESE_DETAIL_REQUEST = 'GET_CHINESE_DETAIL_REQUEST';
export const GET_CHINESE_DETAIL_SUCCESS = 'GET_CHINESE_DETAIL_SUCCESS';
export const GET_CHINESE_DETAIL_FAIL = 'GET_CHINESE_DETAIL_FAIL';

export const UPDATE_CHINESE_REQUEST = 'UPDATE_CHINESE_REQUEST';
export const UPDATE_CHINESE_SUCCESS = 'UPDATE_CHINESE_SUCCESS';
export const UPDATE_CHINESE_FAIL = 'UPDATE_CHINESE_FAIL';
export const UPDATE_CHINESE_RESET = 'UPDATE_CHINESE_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
