export const CREATE_DRINK_REQUEST = 'CREATE_DRINK_REQUEST';
export const CREATE_DRINK_SUCCESS = 'CREATE_DRINK_SUCCESS';
export const CREATE_DRINK_FAIL = 'CREATE_DRINK_FAIL';
export const CREATE_DRINK_RESET = 'CREATE_DRINK_RESET';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ALL_DRINK_REQUEST = 'ALL_DRINK_REQUEST ';
export const ALL_DRINK_SUCCESS = 'ALL_DRINK_SUCCESS';
export const ALL_DRINK_FAIL = 'ALL_DRINK_FAIL';

export const UPDATE_DRINK_REQUEST = 'UPDATE_DRINK_REQUEST';
export const UPDATE_DRINK_SUCCESS = 'UPDATE_DRINK_SUCCESS';
export const UPDATE_DRINK_FAIL = 'UPDATE_DRINK_FAIL';
export const UPDATE_DRINK_RESET = 'UPDATE_DRINK_RESET';

export const SINGLE_DRINK_REQUEST = 'SINGLE_DRINK_REQUEST';
export const SINGLE_DRINK_SUCCESS = 'SINGLE_DRINK_SUCCESS';
export const SINGLE_DRINK_RESET = 'SINGLE_DRINK_RESET';
export const SINGLE_DRINK_FAIL = 'SINGLE_DRINK_FAIL';

export const DELETE_DRINK_REQUEST = 'DELETE_DRINK_REQUEST';
export const DELETE_DRINK_SUCCESS = 'DELETE_DRINK_SUCCESS';
export const DELETE_DRINK_RESET = 'DELETE_DRINK_RESET';
export const DELETE_DRINK_FAIL = 'DELETE_DRINK_FAIL';
