export const INDIAN_DISH_REQUEST = 'INDIAN_DISH_REQUEST';
export const INDIAN_DISH_SUCCESS = 'INDIAN_DISH_SUCCESS';
export const INDIAN_DISH_FAIL = 'INDIAN_DISH_FAIL';

export const NEW_INDIAN_DISH_REQUEST = 'NEW_INDIAN_DISH_REQUEST';
export const NEW_INDIAN_DISH_SUCCESS = 'NEW_INDIAN_DISH_SUCCESS';
export const NEW_INDIAN_DISH_FAIL = 'NEW_INDIAN_DISH_FAIL';
export const NEW_INDIAN_DISH_RESET = 'NEW_INDIAN_DISH_RESET';

export const DELETE_INDIAN_REQUEST = 'DELETE_INDIAN_DISH_REQUEST';
export const DELETE_INDIAN_SUCCESS = 'DELETE_INDIAN_DISH_SUCCESS';
export const DELETE_INDIAN_RESET = 'DELETE_INDIAN_DISH_RESET';
export const DELETE_INDIAN_FAIL = 'DELETE_INDIAN_DISH_FAIL';

export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST';
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS';
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL';

export const INDIAN_SINGLE_REQUEST = 'INDIAN_SINGLE_REQUEST ';
export const INDIAN_SINGLE_SUCCESS = 'INDIAN_SINGLE_SUCCESS';
export const INDIAN_SINGLE_FAIL = 'INDIAN_SINGLE_FAIL';

export const UPDATE_INDIAN_REQUEST = 'UPDATE_INDIAN_REQUEST';
export const UPDATE_INDIAN_SUCCESS = 'UPDATE_INDIAN_SUCCESS';
export const UPDATE_INDIAN_FAIL = 'UPDATE_INDIAN_FAIL';
export const UPDATE_INDIAN_RESET = 'UPDATE_INDIAN_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
