export const CREATE_PIZZA_REQUEST = 'CREATE_PIZZA_REQUEST';
export const CREATE_PIZZA_SUCCESS = 'CREATE_PIZZA_SUCCESS';
export const CREATE_PIZZA_FAIL = 'CREATE_PIZZA_FAIL';
export const CREATE_PIZZA_RESET = 'CREATE_PIZZA_RESET';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ALL_PIZZA_REQUEST = 'ALL_PIZZA_REQUEST ';
export const ALL_PIZZA_SUCCESS = 'ALL_PIZZA_SUCCESS';
export const ALL_PIZZA_FAIL = 'ALL_PIZZA_FAIL';

export const UPDATE_PIZZA_REQUEST = 'UPDATE_PIZZA_REQUEST';
export const UPDATE_PIZZA_SUCCESS = 'UPDATE_PIZZA_SUCCESS';
export const UPDATE_PIZZA_FAIL = 'UPDATE_PIZZA_FAIL';
export const UPDATE_PIZZA_RESET = 'UPDATE_PIZZA_RESET';

export const SINGLE_PIZZA_REQUEST = 'SINGLE_PIZZA_REQUEST';
export const SINGLE_PIZZA_SUCCESS = 'SINGLE_PIZZA_SUCCESS';
export const SINGLE_PIZZA_RESET = 'SINGLE_PIZZA_RESET';
export const SINGLE_PIZZA_FAIL = 'SINGLE_PIZZA_FAIL';

export const DELETE_PIZZA_REQUEST = 'DELETE_PIZZA_REQUEST';
export const DELETE_PIZZA_SUCCESS = 'DELETE_PIZZA_SUCCESS';
export const DELETE_PIZZA_RESET = 'DELETE_PIZZA_RESET';
export const DELETE_PIZZA_FAIL = 'DELETE_PIZZA_FAIL';
