export const CREATE_SNACKS_REQUEST = 'CREATE_SNACKS_REQUEST';
export const CREATE_SNACKS_SUCCESS = 'CREATE_SNACKS_SUCCESS';
export const CREATE_SNACKS_FAIL = 'CREATE_SNACKS_FAIL';
export const CREATE_SNACKS_RESET = 'CREATE_SNACKS_RESET';

export const GET_ALL_SNACKS_REQUEST = 'GET_ALL_SNACKS_REQUEST ';
export const GET_ALL_SNACKS_SUCCESS = 'GET_ALL_SNACKS_SUCCESS';
export const GET_ALL_SNACKS_FAIL = 'GET_ALL_SNACKS_FAIL';

export const DELETE_SNACK_REQUEST = 'DELETE_SNACK_REQUEST';
export const DELETE_SNACK_SUCCESS = 'DELETE_SNACK_SUCCESS';
export const DELETE_SNACK_RESET = 'DELETE_SNACK_RESET';
export const DELETE_SNACK_FAIL = 'DELETE_SNACK_FAIL';

export const SINGLE_SNACK_REQUEST = 'SINGLE_SNACK_REQUEST';
export const SINGLE_SNACK_SUCCESS = 'SINGLE_SNACK_SUCCESS';
export const SINGLE_SNACK_RESET = 'SINGLE_SNACK_RESET';
export const SINGLE_SNACK_FAIL = 'SINGLE_SNACK_FAIL';

export const UPDATE_SNACK_REQUEST = 'UPDATE_SNACK_REQUEST';
export const UPDATE_SNACK_SUCCESS = 'UPDATE_SNACK_SUCCESS';
export const UPDATE_SNACK_FAIL = 'UPDATE_SNACK_FAIL';
export const UPDATE_SNACK_RESET = 'UPDATE_SNACK_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
