export const CREATE_TABLE_REQUEST = 'CREATE_TABLE_REQUEST';
export const CREATE_TABLE_SUCCESS = 'CREATE_TABLE_SUCCESS';
export const CREATE_TABLE_FAIL = 'CREATE_TABLE_FAIL';
export const CREATE_TABLE_RESET = 'CREATE_TABLE_RESET';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const ALL_TABLE_REQUEST = 'ALL_TABLE_REQUEST ';
export const ALL_TABLE_SUCCESS = 'ALL_TABLE_SUCCESS';
export const ALL_TABLE_FAIL = 'ALL_TABLE_FAIL';

export const UPDATE_TABLE_REQUEST = 'UPDATE_TABLE_REQUEST';
export const UPDATE_TABLE_SUCCESS = 'UPDATE_TABLE_SUCCESS';
export const UPDATE_TABLE_FAIL = 'UPDATE_TABLE_FAIL';
export const UPDATE_TABLE_RESET = 'UPDATE_TABLE_RESET';

export const SINGLE_TABLE_REQUEST = 'SINGLE_TABLE_REQUEST';
export const SINGLE_TABLE_SUCCESS = 'SINGLE_TABLE_SUCCESS';
export const SINGLE_TABLE_RESET = 'SINGLE_TABLE_RESET';
export const SINGLE_TABLE_FAIL = 'SINGLE_TABLE_FAIL';

export const DELETE_TABLE_REQUEST = 'DELETE_TABLE_REQUEST';
export const DELETE_TABLE_SUCCESS = 'DELETE_TABLE_SUCCESS';
export const DELETE_TABLE_RESET = 'DELETE_TABLE_RESET';
export const DELETE_TABLE_FAIL = 'DELETE_TABLE_FAIL';
